apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lkm
resources:
  - ../prod
  - rabbitmq.yaml
patches:
  - path: delete-pulsar-service.yaml
  - path: delete-pulsar-statefulset.yaml
  - path: patch-bus.yaml
